theme = "awesome-identity"
baseURL = "https://tynrare.github.io"
title = "tynrare's persona page"


## Profile Configurations
[params.profile]
  portrait = "/images/portrait-default.jpg"
  firstname = "Tim"
  lastname = "Borisov"
  title = "Software engineer / tynrare"
  bio = """I totally stole personal description from [original creator](https://www.posquit0.com/) of this page just because I love how it sounds and it very close to me

  ...

  5+ years experience specializing in the frontend and gamedev development, infrastructure automation, and project management and whatever you need to do when you develop software.

Super nerd who loves Vim, Linux and enjoys to customize all of the development environment.

Interested in devising a better problem-solving method for challenging tasks, and learning new technologies and tools if the need arises.

  ...

  Also in love with graphics, CLIs, problem solving and process optimisation.
  """

## Contacts Configurations
[params.contacts]
  email = "tymonr@yandex.ru"
  github = "tynrare"
  twitter = "tynrare"
  linkedin = "tynrare"
  stackoverflow = "7829041"
  keybase = "tynrare"

[params.actions.resume]
  name = "My CV"
  url = "http://www.tynrare.net/docs/resume-2020.pdf"

[params.actions.exams]
  name = "My exams"
  url = "http://www.tynrare.net/apps/exams/"

[params.actions.bible]
  name = "My Bible"
  url = "https://medium.com/swlh/62-lessons-from-50-years-of-software-experience-2db0f400f706"

## Footer Configurations
[params.footer]
  copyright = "© 2020 tynrare. [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
  poweredBy = true
